if (!require('httr')) install.packages('httr', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!require('rjson')) install.packages('rjson', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!require('rsvg')) install.packages('rsvg', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!require('twitteR')) install.packages('twitteR', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!require('jsonlite')) install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!require('ggplot2')) install.packages('ggplot2', dependencies=TRUE, repos='http://cran.rstudio.com/')
